### ISSUE TITLE
Interpreting results

### ISSUE THREAD

**Issue by smorabit** [SydneyBioX/scDC#2]
Hi I am just writing to ask about how to properly interpret the results from scDC correctly. In the [vignette](https://sydneybiox.github.io/scDC/articles/vignette.html), there are two clusters, two conditions, and two samples in each condition. Following the GLM fitting, a summary table is shown for fixed and random effects. In the vignette, was scDC used to test if there is a significant difference in the composition of each cluster with respect to the two conditions, or is it testing something else? It is not clear to me what the different rows are representing in the output table. It would be great if you could provide an explanation!

**Comment by ycao6928** [comment]
Dear Smorabit,

Thank you for trying out our package. 

I'll copy the reply to your email here as well so that other people who might have the same question could also see it. 

The model is fitted using a generalised linear model. In linear regression, one level of a categorical variable is always treated as the baseline/reference level which is not shown in the model output, and all estimation is relative to this reference level.
 
In the case of comparing the proportion of cell types, the first cell type is used as the baseline, and the model output shows whether proportion of cell type 2 to cell type 1 is different for each condition, and whether proportion of cell type 3 to cell type 1 is different for each condition etc etc. This is why the output is different from say a standard t-test, where it’s just doing individual comparison of cell type 1 in condition 1 vs cell type 1 in condition 2 and giving an output for each cell type.
